export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const FETCH_NOW_PLAYING_SUCCESS = 'FETCH_NOW_PLAYING_SUCCESS';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ON_SWIPER_SCROLL_END_SUCCESS = 'ON_SWIPER_SCROLL_END_SUCCESS';
export const SWIPER_IMAGE_INDEX = 'SWIPER_IMAGE_INDEX';